const mongoose = require('mongoose');
const productSchema = new mongoose.Schema({
    productName: { type: String, required: true },
    productCode: { type: String, required: true },
    categoryId: { type: mongoose.Schema.Types.ObjectId, ref: 'Category', required: true },
    categoryName: { type: String, required: true },
    variantName: { type: String },
    variantId: { type: mongoose.Schema.Types.ObjectId, ref: 'Variant' },
    description: { type: String },
    standardSize: [{ type: String }],
    customization: { type: Boolean, default: false },
    customizationId: { type: mongoose.Schema.Types.ObjectId, ref: 'Customization' },
    stock: { type: Number, required: true, default: 0 },
    status: { type: String, default: "In Stock", enum: ["In Stock", "Out of Stock"] },
    actualPrice: { type: Number, required: true },
    sellingPrice: { type: Number, required: true },
    tags: [{ type: String }],
    tax: { type: Number },
    couponCode: { type: String },
    color: { type: String },
    availability: { type: Boolean, default: true },
    images: [{ type: String }],
    isDeleted: { type: Boolean, default: false },
    createdAt: { type: Date, default: Date.now },

    // Design Lab
    isDesignLab: { type: Boolean, default: false },
    letterPrintingColor: { type: String },
    letterPrintingText: { type: String },
    productColor: { type: String },
    kidsSize: [{ type: String }],
    adultsSize: [{ type: String }],
    youthSize: [{ type: String }],
    womenSize: [{ type: String }],
});
module.exports = mongoose.model('Product', productSchema);
